### ISSUE TITLE
You may be interested in looking at UIMF format

### ISSUE THREAD

**Issue by dylanhross** [wkumler/mzsql#12]
I took a look at the README  while grabbing the test data you linked from this repo, and it occurred to me you might be interested in looking at the UIMF format. It is a raw MS data format developed and used widely at PNNL that uses SQLite and an efficient compressed format for spectra.

https://ieeexplore.ieee.org/abstract/document/5380883
https://github.com/PNNL-Comp-Mass-Spec/UIMF-Library

**Comment by wkumler** [comment]
Neat! Thanks for the recommendation - looks like it'd be a really good thing to compare to but I don't think I speak enough C# to know how to interface with it. I can't find an easy way to convert .mzML to .UIMF even though the demo files are in fact just SQLite databases which means that the queries should be the same. I'm also struggling to figure out how to perform the three basic operations - chromatogram extraction, single scan extraction, and RT range extraction - that I'm testing these solutions on. 

I may have to come back to the UIMF format later and/or request some additional documentation for the novice user like me to include it in the project!
