### ISSUE TITLE
mzDB things

### ISSUE THREAD

**Issue by wkumler** [wkumler/mzsql#3]
mzDB tasks:
  - [x] Conversion code:
  - [ ] Single spectrum
  - [ ] Chromatogram (given m/z range)
  - [ ] Multi-spectrum RT range

**Comment by SamLaRue** [comment]
MZBD parser/extractor for chromatogram

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
from pyteomics import mzdb

#Open a connection to the SQLite database
conn = sqlite3.connect("msdata.sqlite")

#Read the mzDB file and process each MS1 spectrum
with mzdb.MzDB('180205_Poo_TruePoo_Full1.mzDB') as reader:
    for spectrum in reader:
        if spectrum['ms level'] == 1:
            mz_vals = spectrum['m/z array']
            int_vals = spectrum['intensity array']
            rt_val = spectrum['scan start time']

            # Create a DataFrame and append to the SQL database
            df_scan = pd.DataFrame({'mz': mz_vals, 'int': int_vals, 'rt': [rt_val] * len(mz_vals)})
            df_scan.to_sql("MS1", conn, if_exists="append", index=False)

conn.close()

#Define a function to retrieve chromatogram data
def get_chrom_sqlite3(database):
   conn = sqlite3.connect(database)
    query_data = pd.read_sql_query("SELECT * FROM MS1 WHERE ABS(mz-118.0865) <= 0.001", conn)
    conn.close()
    return query_data

#Fetch chromatogram data and plot
chrom_data = get_chrom_sqlite3("msdata.sqlite")
#print(chrom_data)

#Plot the chromatogram
plt.plot(chrom_data["rt"], chrom_data["int"])
plt.xlabel("Retention Time (minutes)")
plt.ylabel("Intensity")
plt.title("Chromatogram for m/z ~ 118.0865")
plt.show()

**Comment by wkumler** [comment]
Windows command line used to produce the mzDB file from the original mzML:

```
raw2mzDB.exe -i 180205_Poo_TruePoo_Full1.mzML -o 180205_Poo_TruePoo_Full1.mzDB -c 1
```

Apparently the `-c 1` is necessary if the data's already been centroided
